name: CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install .Net Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x
            9.0.x
          include-prerelease: true
      - name: Install dotnet-script
        run: dotnet tool install dotnet-script --global

      - name: Run build script
        run: dotnet-script build/Build.csx

  build-mac:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
      - name: Install .Net Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x
            9.0.x
          include-prerelease: true
      - name: Install dotnet-script
        run: dotnet tool install dotnet-script --global

      - name: Run build script
        run: dotnet-script build/Build.csx

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install .Net Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x
            9.0.x
          include-prerelease: true
      - name: Install dotnet-script
        run: dotnet tool install dotnet-script --global

      - name: Run build script
        run: dotnet-script build/Build.csx
        env: # Or as an environment variable
          GITHUB_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IS_SECURE_BUILDENVIRONMENT: ${{ secrets.IS_SECURE_BUILDENVIRONMENT }}
          NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
